name: Trigger Main Repo Update

on:
  push:
    branches:
      - main  # Change this to the branch you want to track

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      
    - name: Install API response parser
      run: |
         sudo apt-get update
         sudo apt-get install -y jq
         
    - name: Retrive User Details
      run: | 
          user_name=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/user)
          echo "user_login=$(echo $user_name | jq -r '.login')" >> $GITHUB_ENV
          
    - name: Set Access Token
      run: |
          if [ "${{ github.actor }}" = "${{ env.user_login }}" ]; then
            echo "token=${{ secrets.GIT_TOKEN }}" >> $GITHUB_ENV
          fi
    - name: Access the Project Details files
      run: |
         curl -H "Authorization: token ${{ env.token }}" \
         -H "Accept:application/vnd.github.v3.raw" \
         -O \-L "https://api.github.com/repos/RaajGurunathan/NewProject/contents/projectNames.json?ref=main"
       
    - name: Trigger workflow in main repository
      run: |
        values=$(cat projectNames.json | jq -r '.projects[]')
        for value in $values; do
        curl -X POST -H "Authorization: token ${{ env.token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/RaajGurunathan/${value}/dispatches \
          -d '{"event_type":"update_submodule"}'
        done
