name: Trigger Main Repo Update

on:
  push:
    branches:
      - main  # Change this to the branch you want to track

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
    - name: Get access token
      uses: github-actions/gettoken@v1
      id: token
      with:
       github_token: ${{secrets.GITHUB_TOKEN}}
       run: echo "Access token:${{ steps.token.outputs.token }}"
      
    - name: Trigger workflow in main repository
      run: |
        curl -X POST -H "Authorization: token ${{ steps.token.outputs.token }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/RaajGurunathan/Project/dispatches \
          -d '{"event_type":"update_submodule"}'
