name: Trigger Main Repo Update

on:
  push:
    branches:
      - main  # Change this to the branch you want to track

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
    - name: Set PAT Token based on Commiter 
      id: set-pat 
      run: |
        COMMIT_AUTHOR=$(git log -1 --pretty=format:'%ae')
        if COMMIT_AUTHOR == "rajkumar.gurunathan90@gmail.com"; then
            echo "::set-output name=pat::${{secrets.GIT_TOKEN}}"
        fi
    - name: Trigger workflow in main repository
      run: |
        curl -X POST -H "Authorization: token ${{steps.set-pat.outputs.pat}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/RaajGurunathan/Project/dispatches \
          -d '{"event_type":"update_submodule"}'
