name: Trigger Main Repo Update

on:
  push:
    branches:
      - main  # Change this to the branch you want to track

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch PAT token based on committer email
      id: fetch_token
      run: |
        COMMITTER_EMAIL="${GITHUB_ACTOR}@users.noreply.github.com"
        TOKEN=$(curl -X POST -H "Content-Type: application/json" -d "{\"committer_email\": \"${COMMITTER_EMAIL}\"}" https://github.com/api/fetch-token)
        echo "TOKEN=${TOKEN}" >> $GITHUB_ENV

    - name: Trigger workflow in main repository
      run: |
        curl -X POST -H "Authorization: token ${{ env.TOKEN }}}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/RaajGurunathan/Project/dispatches \
          -d '{"event_type":"update_submodule"}'
