name: Trigger Main Repo Update

on:
  push:
    branches:
      - main  # Change this to the branch you want to track

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger workflow in main repository
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/RaajGurunathan/Project/dispatches \
          -d '{"event_type":"update_submodule"}'
