name: Trigger Main Repo Update

on:
  push:
    branches:
      - main  # Change this to the branch you want to track

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    
    - name: Set Access Token
      run: |
          username="${{ github.actor }}"
          if username == "RaajGurunathan"; then
            echo "token=${{ secrets.GIT_TOKEN }}" >> $GITHUB_ENV
            echo "Using token: ${{ env.token }}"
          fi
    - name: Trigger workflow in main repository
      run: |
        curl -X POST -H "Authorization: token ${{ env.token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/RaajGurunathan/Project/dispatches \
          -d '{"event_type":"update_submodule"}'
